baseURL = "https://docs.arcion.io/"
canonifyURLs = "true"
languageCode = "en-us"
theme = "book"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
[params]
  BookTheme = 'light'
  BookLogo = '/arcion-horizontal.png'
  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/arcionlabs/arcion-docs'
  BookEditPath = 'issues/new/choose'

[deployment]
  [[deployment.targets]]
    name="replicant-docs"
    URL="gs://docs.arcion.io"
