{
 "title": "Arcion Replication Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "replication_id", "label": "Replication Id", "query": { "query": "label_values(replication_id)" } },
   { "name": "selected_table", "label": "Table", "query": { "query": "label_values(table)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Replication statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total rows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(current_phase) (total_rows{replication_id=\"$replication_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak rows per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(peak_rows_per_sec{replication_id=\"$replication_id\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "total_lag{replication_id=\"$replication_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot total rows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(current_phase) (snapshot_total_rows{replication_id=\"$replication_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(current_phase) (active_threads{replication_id=\"$replication_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average rows per second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(current_phase) (avg_rows_per_sec{replication_id=\"$replication_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(current_phase) (total_lag{replication_id=\"$replication_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max without(current_phase) (transactions{replication_id=\"$replication_id\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max without(current_phase) (failed_transactions{replication_id=\"$replication_id\"})",
     "legendFormat": "Failed transactions"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max without(current_phase) (free_memory{replication_id=\"$replication_id\"})",
     "legendFormat": "Free memory"
    },
    {
     "expr": "max without(current_phase)(max_memory{replication_id=\"$replication_id\"})",
     "legendFormat": "Max memory"
    },
    {
     "expr": "max without(current_phase)(total_memory{replication_id=\"$replication_id\"})",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max without(current_phase) (buffered_operations{replication_id=\"$replication_id\"})",
     "legendFormat": "Buffered operations"
    },
    {
     "expr": "max without(current_phase) (buffered_transactions{replication_id=\"$replication_id\"})",
     "legendFormat": "Buffered transactions"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max without(current_phase)(replication_lag{replication_id=\"$replication_id\"})",
     "legendFormat": "Replication lag"
    },
    {
     "expr": "max without(current_phase)(total_lag{replication_id=\"$replication_id\"})",
     "legendFormat": "Total lag"
    }
   ]
  },
  { "title": "Table replication statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Row details per table",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "table_inserted_rows{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "inserted-{{table}}"
    },
    {
     "expr": "table_deleted_rows{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "deleted-{{table}}"
    },
    {
     "expr": "table_replaced_rows{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "replaced-{{table}}"
    }
   ]
  },
  {
   "title": "Affected rows per table",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "table_affected_rows{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "table_lag{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "lag-{{table}}"
    },
    {
     "expr": "table_replication_lag{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "replication-lag-{{table}}"
    }
   ]
  },
  {
   "title": "Buffered operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "table_buffered_operations{table=~\"$selected_table\", replication_id=\"$replication_id\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Rows per second",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "table_rows_per_sec{replication_id=\"$replication_id\", table=~\"$selected_table\"}",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}