name: Deploy Preview

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: 
    pull_request:
                branches:
                        - dev
    workflow_dispatch: #for-testing
    
jobs:
      Deploy-Preview:  
            runs-on: ubuntu-latest
            steps:

                  - uses: actions/checkout@v3

                  - name: Install Vercel CLI
                    run: npm install --global vercel

                  - name: Install Hugo
                    run: |
                      HUGO_VERSION="0.121.2"
                      wget -O hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"
                      tar -xzvf hugo.tar.gz
                      sudo mv hugo /usr/local/bin/hugo
                      hugo version

                  - name: Pull Vercel Environment Information
                    run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

                  - name: Build Project Artifacts 
                    run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

                  - name: Deploy Project Artifacts
                    run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
